### ISSUE TITLE
Ripple from the middle?

### ISSUE THREAD

**Issue by TheArhaam** [handoing/flutter_page_transition#3]
The only ripple options available are Left, Right, LeftDown & RightDown
Adding a middle ripple to the RippleClipper would be really helpful and convenient 

ex:
```
Map center = <String, Offset>{
      'Left': Offset(0, size.height),
      'Right': Offset(size.width, size.height),
      'LeftDown': Offset(0, 0),
      'RightDown': Offset(size.width, 0),
      'Middle': Offset(size.width*0.5,size.height*0.5),
    };
```

I'm not exactly sure but would that work?

**Comment by handoing** [comment]
It's a good suggestion, I will add it.
